### PR TITLE
Update to Gulp 4 and switch to eslint

### PR DESCRIPTION
**Pull request by tomap**
Also update all gulp plugins to latest

### CODE REVIEW

**Comment by tomap** [comment]
There is a breaking change (require nodejs >= 6.9) that could deserve a version bump

**Review by yoshinorin — CHANGES_REQUESTED** [review]
Would you fix `.travis.yml` node_js versions?
I think maybe CI is failing that reason.

**Comment by tomap** [comment]
Done

**Review by yoshinorin — APPROVED** [review]
LGTM 👍

**Pull request merged**
